TECH-1545 : use webpack shared configuration
Jahia/jahia-ui-root pull request #165
Opened 2024-01-02 19:29 UTC by dgriffon

https://jira.jahia.org/browse/TECH-1545

2024-01-05 15:26 UTC, jsinovassin requested changes

2024-01-05 15:26 UTC, jsinovassin commented on webpack.config.js
>                      './init': './src/javascript/init',
You could remove this line, the init is already exposed by the getModuleFederationConfig

2024-01-05 15:26 UTC, jsinovassin commented on webpack.config.js
>                  library: { type: "assign", name: "appShell.remotes.jahiaUi" },
Library is not necessary, it will be added by getModuleFederationConfig which will use the name property that you set

2024-01-10 09:32 UTC, dgriffon commented
Won't be done yet in current jahia parent version ( < 8.2.x )

2024-01-10 09:32 UTC, closed without merging